// Generated by CoffeeScript 1.8.0
(function() {
  var Graph,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  $(document).ready(function() {
    var graph;
    graph = new Graph({
      el: $('#surface svg')
    });
    return console.log(graph);
  });

  Graph = (function(_super) {
    __extends(Graph, _super);

    function Graph() {
      return Graph.__super__.constructor.apply(this, arguments);
    }

    Graph.prototype.initialize = function() {
      Graph.__super__.initialize.apply(this, arguments);
      return console.log('init');
    };

    return Graph;

  })(Avispa);

}).call(this);

//# sourceMappingURL=example.js.map
