// Generated by CoffeeScript 1.8.0
(function() {
  var ForemanGroup, Graph,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  $(document).ready(function() {
    var graph, group;
    graph = new Graph({
      el: $('#surface svg')
    });
    group = new ForemanGroup({
      model: new Backbone.Model({
        title: 'Group 1'
      }),
      parent: null,
      position: new Backbone.Model({
        x: 30,
        y: -50,
        w: 100,
        h: 100,
        fill: '#fcc'
      })
    });
    graph.$groups.append(group.$el);
    group = new ForemanGroup({
      model: new Backbone.Model({
        title: 'Group 2'
      }),
      parent: null,
      position: new Backbone.Model({
        x: 40,
        y: 60,
        w: 100,
        h: 100,
        fill: '#fcc'
      })
    });
    return graph.$groups.append(group.$el);
  });

  Graph = (function(_super) {
    __extends(Graph, _super);

    function Graph() {
      return Graph.__super__.constructor.apply(this, arguments);
    }

    Graph.prototype.initialize = function() {
      return Graph.__super__.initialize.apply(this, arguments);
    };

    return Graph;

  })(Avispa);

  ForemanGroup = (function(_super) {
    __extends(ForemanGroup, _super);

    function ForemanGroup() {
      return ForemanGroup.__super__.constructor.apply(this, arguments);
    }

    ForemanGroup.prototype.initialize = function() {
      ForemanGroup.__super__.initialize.apply(this, arguments);
      this.$label = $SVG('text').attr('dx', '0.5em').attr('dy', '1.5em').text(this.model.get('title')).appendTo(this.$el);
      this.render();
      return this;
    };

    ForemanGroup.prototype.render = function() {
      this.$rect.attr('x', this.position.get('x')).attr('y', this.position.get('y'));
      this.$label.attr('x', this.position.get('x')).attr('y', this.position.get('y'));
      return this;
    };

    ForemanGroup.prototype.OnMouseDown = function(event) {
      $('.contextMenu').hide();
      return ForemanGroup.__super__.OnMouseDown.apply(this, arguments);
    };

    ForemanGroup.prototype.OnContextMenu = function(event) {
      if (event.shiftKey) {
        return;
      }
      return cancelEvent(event);
    };

    return ForemanGroup;

  })(Avispa.Group);

}).call(this);

//# sourceMappingURL=example.js.map
